# FIX: ลบบรรทัด 'version' ที่ล้าสมัยออกไป
services:
  # Service สำหรับ Backend (PHP API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartport-backend
    ports:
      - "8000:80"
    volumes:
      - backend-uploads:/var/www/html/uploads
    environment:
      # Environment Variables เหล่านี้จะถูกอ่านมาจากไฟล์ .env
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smartport-net
    restart: unless-stopped

  # Service สำหรับ Frontend (Vite App)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend
    container_name: smartport-frontend
    ports:
      - "8081:80" # ใช้ port 8081
    depends_on:
      - backend
    networks:
      - smartport-net
    restart: unless-stopped

  # Service สำหรับ Database (MySQL)
  db:
    image: mysql:8.0
    container_name: smartport-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql_database_design.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./photo_management_system.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - smartport-net
    restart: unless-stopped

networks:
  smartport-net:
    driver: bridge

volumes:
  db-data:
  backend-uploads:
