-- Initialize the base Smart Port schema.
CREATE DATABASE IF NOT EXISTS civil_service_mgmt CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE civil_service_mgmt;

-- Core lookup table for name prefixes.
CREATE TABLE prefixes (
    prefix_id INT PRIMARY KEY AUTO_INCREMENT,
    prefix_code VARCHAR(10) UNIQUE NOT NULL,
    prefix_name_th VARCHAR(50) NOT NULL,
    prefix_name_en VARCHAR(50),
    prefix_short VARCHAR(20),
    gender ENUM('M', 'F', 'A') DEFAULT 'A',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Core civil servant profile table.
CREATE TABLE civil_servants (
    servant_id INT PRIMARY KEY AUTO_INCREMENT,
    employee_id VARCHAR(20) UNIQUE NOT NULL,
    citizen_id VARCHAR(13) UNIQUE NOT NULL,
    prefix_id INT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    appointment_date DATE NOT NULL,
    retirement_date DATE,
    servant_status ENUM('active', 'retired') DEFAULT 'active',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (prefix_id) REFERENCES prefixes(prefix_id)
);

-- Uploaded photo records for each civil servant.
CREATE TABLE civil_servant_photos (
    photo_id INT PRIMARY KEY AUTO_INCREMENT,
    servant_id INT NOT NULL,
    photo_type ENUM('profile', 'formal') NOT NULL DEFAULT 'profile',
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    photo_status ENUM('active', 'pending_approval') DEFAULT 'pending_approval',
    is_primary BOOLEAN DEFAULT FALSE,
    upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (servant_id) REFERENCES civil_servants(servant_id)
);

-- Version records are generated by backend/helpers.php instead of a DB routine.
CREATE TABLE IF NOT EXISTS photo_versions (
    version_id INT PRIMARY KEY AUTO_INCREMENT,
    photo_id INT NOT NULL,
    version_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (photo_id) REFERENCES civil_servant_photos(photo_id)
);

-- Current profile view.
CREATE VIEW v_civil_servants_current AS
SELECT
    cs.servant_id,
    CONCAT(p.prefix_name_th, cs.first_name, ' ', cs.last_name) AS full_name,
    csp.file_path AS photo_path
FROM civil_servants cs
LEFT JOIN prefixes p ON cs.prefix_id = p.prefix_id
LEFT JOIN civil_servant_photos csp
    ON cs.servant_id = csp.servant_id
    AND csp.is_primary = TRUE;

-- Sample data for a clean bootstrap.
INSERT INTO prefixes (prefix_code, prefix_name_th) VALUES ('MR', 'นาย');
INSERT INTO civil_servants (
    employee_id,
    citizen_id,
    prefix_id,
    first_name,
    last_name,
    birth_date,
    appointment_date
) VALUES (
    'EMP001',
    '1234567890123',
    1,
    'สมชาย',
    'ไทยแท้',
    '1980-01-01',
    '2000-01-01'
);
